version: "3.8"

services:
  db:
    image: postgres:13.3
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local #Here we are using the already existing .env.local file
    ports:
      - "5432:5432"

volumes:
  data:
